coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        required: yes

    patch:
      default:
        target: 80%
        required: yes
        threshold: 0.5%

  base: auto

parsers:
  javascript:
    enable_partials: true

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no
